baseURL = 'https://oomycetemolgen.github.io/'
languageCode = 'en-us'
title = 'OMGN'
theme = [ "kmin", "kphoto"]
[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "What are Oomycetes?"
  weight = 10
  identifier = "oomycetes"
  url = "/about-oomycetes/"
